name: Rust

on:
  push:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y devscripts equivs

    - uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        mk-build-deps
        sudo apt-get install -y ./*-build-deps_*.deb

    - name: Build package
      run: |
        git clean -f
        debuild --no-tgz-check -us -uc
        mkdir -p output
        mv ../*.deb output/

    - name: Archive debian package
      uses: actions/upload-artifact@v3
      with:
        name: debs
        path: |
          output/*.deb
